Change type export in package.json
talkjs/country-flag-emoji-polyfill pull request #12
Opened 2024-01-08 09:26 UTC by RndUsername

The module doesn't compile in Typescript because the type export is not set correctly.

2024-01-08 12:30 UTC, eteeselink requested changes
Thanks for your PR! I have a doubt about it though, see comments below.

2024-01-08 12:30 UTC, eteeselink commented on package.json
> -  "types": "./dist/index.d.ts",
According to https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html it very much does belong here. Can you explain why it doesn't?

In short, I'm worried that there are setups that expect it to be in `types` and won't look in `export.types`. Can you explain more about what all this means?

2024-01-17 08:23 UTC, RndUsername commented
To be honest I don't really know why but if I use it as is, I get the build error `Could not find a declaration file for module 'country-flag-emoji-polyfill'`. If you pull [my project](https://github.com/RndUsername/osmu-wiki/tree/da05792f20adf76a832b26fba2dae91cbcbbc3b3) and run `npm run build` you can see that for yourself. I hope this helps.

Could we maybe put `"types": "./dist/index.d.ts"` into both places? Leave it like before and additionally put into `"exports"`?

2024-01-17 08:27 UTC, eteeselink commented
Does this PR fix it for you? https://github.com/talkjs/country-flag-emoji-polyfill/pull/13

2024-01-17 08:31 UTC, RndUsername commented
I could not get my PR installed locally but if do the change by hand, it works.

2024-01-17 08:32 UTC, RndUsername commented
Ah, sorry I missunderstud, I need to check that

2024-01-17 08:39 UTC, RndUsername commented
Yes! It works like a charm!

2024-01-19 11:32 UTC, eteeselink commented
Fixed in #13 and published as [0.1.7](https://www.npmjs.com/package/country-flag-emoji-polyfill/v/0.1.7). Thanks for your help with reporting & testing this!

2024-01-19 11:32 UTC, closed without merging